### ISSUE TITLE
Running "predict training" fails with "Invalid fold"

### ISSUE THREAD

**Issue by ghost** [tqbl/dcase2018_task2#2]
When running `predict training`, the `--fold` value seems to be required. 

The code in main.py:
```
    if dataset.name == 'training':
        if fold == -1:
            raise ValueError('Invalid fold: %d' % fold)
```

Does this mean that `--fold` is required when training too? 

I have successfully ran 3 steps: 
- preprocessing
- feature extraction
- training

However, prediction step fails. Please help with short explanation if possible?

**Comment by tqbl** [comment]
`predict training` means you want to compute predictions for (a subset of) the training set. This command doesn't really make sense if you train the model on the whole training set. Instead, you train the model on folds 1, 2, 3, and 4, for example, and then compute predictions for fold 0.

If you want to compute predictions for the training set, you do indeed need to train the model using the `--fold` option.
```
python task2/main.py train --fold 0
python task2/main.py predict training --fold 0
```
Do this for all the folds so that you have predictions for the whole training set.

On the other hand, if you want to compute predictions for the test set, run:
```
python task2/main.py predict test
```

I hope that makes sense.

**Comment by ghost** [comment]
I would like to avoid using folds, to make things simpler. 
Since I haven't used folds in training, I trained on the whole set - what would be the next step after I trained? How to I verify my test set?

**Comment by tqbl** [comment]
Sorry, I forgot that I didn't implement evaluation of the test set. I can do this later this week, or perhaps you can implement it yourself. See the `evaluate_audio_tagging()` function in `task2/main.py`. Replace the first two blocks of code.

Other than that, you can run the prediction using the command I mentioned in the previous comment. However, you might have to modify one file before doing this. In `task2/config/prediction.py`, you should see this line:
```
prediction_epochs = 'val_map'
```
Change this so that it's a list of epoch numbers instead. You could specify the last n epochs, for example. The reason is that training on the whole training set means that there is no validation set.

**Comment by ghost** [comment]
Ahhh that's dissapointing. :-) 

I think I'm not ready to make changes to the code yet, but I can try later on. Let me study the whole thing a bit more. 
 
Thanks for helping. 👍

**Comment by tqbl** [comment]
No problem, and sorry I couldn't help more. Since the changes should be quite small, I think I might even be able to make them by tonight once I return home. Give it a day at most.

**Comment by tqbl** [comment]
For the time being, can you try the patch I've attached and see if it works?
Put it in the root directory of the project and run
```
patch -p1 <eval_test.txt
```
Then you should be able to evaluate the model using
```
python task2/main.py evaluate test
```

[eval_test.txt](https://github.com/tqbl/dcase2018_task2/files/4150738/eval_test.txt)

**Comment by ghost** [comment]
The patch doesn't work. 
```
 File "task2/main.py", line 284, in evaluate_audio_tagging
    y_pred = pd.read_csv(path, index_col=0).loc[df.index].values
predictions\\jul31_vgg13\\predictions_test.csv' does not exist
```

Should I somehow generate the missing file?

**Comment by tqbl** [comment]
Did you remember to generate the predictions?
```
python task2/main.py predict test
```
That should save the predictions in `<work_path>/predictions/jul31_vgg13/predictions_test.csv`. If not, let me know where they were saved. I may have made a mistake.

As a side note, you can change the training ID (currently 'jul31_vgg13') in `task2/config/training.py`.

**Comment by ghost** [comment]
I did try to generate predictions, but I got 
```
  File "task2/main.py", line 352, in _determine_epochs
    history = io.read_training_history(path, ordering=spec)
  File "task2\file_io.py", line 27, in read_training_history
    df = pd.read_csv(path, index_col=0)
FileNotFoundError: File b'logs\\jul31_vgg13\\all\\history.csv' does not exist
```
So, there is no history file, and the history file isn't generated unless `--fold` option is used? I am not using fold. Back to square one. :-)

**Comment by tqbl** [comment]
Like I said, you have to modify `task2/config/prediction.py` to use specific epochs.
See the second half of https://github.com/tqbl/dcase2018_task2/issues/2#issuecomment-581499398. So something like this:
```
prediction_epochs = [35, 37, 39]
```

**Comment by tqbl** [comment]
Let me know if you got everything working. I'll properly update the code if you have.

**Comment by ghost** [comment]
Sorry for delay.
`predict test` finaly went OK. 
However, last step `evaluate test` failed. 
The error is: 
```
File "task2\evaluation.py", line 32, in evaluate_audio_tagging
    class_scores = compute_audio_tagging_scores(y_true, y_pred, y_pred_b).T
  File "task2\evaluation.py", line 70, in compute_audio_tagging_scores
    y_true, y_pred_b, average=average)

raise ValueError("Multi-label binary indicator input with "
ValueError: Multi-label binary indicator input with different numbers of labels
```

**Comment by tqbl** [comment]
Can you upload the predictions that were generated? It should be a `.csv` file in `<work_path>/predictions/<training_id>/`.
I've seen this problem before, so hopefully it shouldn't be difficult to fix.

**Comment by ghost** [comment]
Here it is:
[danijel-predictions.zip](https://github.com/tqbl/dcase2018_task2/files/4165448/danijel-predictions.zip)

Bare in mind that I trained and tested on a very limited number of input samples, to speed things up.

**Comment by tqbl** [comment]
Thanks. That explains it. The code isn't really robust against incomplete predictions, especially when some of the classes are left out completely, which is why that error was thrown. I have hopefully fixed that now. Try this latest patch, but apply it to the original code (not on top of the other patch).

As an aside, you might want to check out https://github.com/tqbl/ood_audio. Although the application is different, you can think of it as a more up to date version of this repository. This is one of the issues that was fixed in that repo. I have tried to fix issues in this repo too, but I sometimes forget.

[eval_test2.txt](https://github.com/tqbl/dcase2018_task2/files/4166367/eval_test2.txt)

**Comment by ghost** [comment]
Will test tommorrow. 
I did have problems with classes left out completely, but then I made sure that both test and train contain all of the 41 classes, so that should've not mattered.

**Comment by ghost** [comment]
The fix doesn't help unfortunatelly. 
I've repeated all steps: preprocess-extract-train-predict-evaluate, but the last one failed:

```
File "task2/main.py", line 293, in evaluate_audio_tagging
    y_true, y_pred, threshold=cfg.threshold)
  File "task2\evaluation.py", line 32, in evaluate_audio_tagging
    class_scores = compute_audio_tagging_scores(y_true, y_pred, y_pred_b).T
  File "task2\evaluation.py", line 70, in compute_audio_tagging_scores
    y_true, y_pred_b, average=average)
  File ".virtualenvs\Surrey3\lib\site-packages\sklearn\metrics\classification.py", line 1033, in precision_recall_fscore_support
    present_labels = unique_labels(y_true, y_pred)
  File ".virtualenvs\Surrey3\lib\site-packages\sklearn\utils\multiclass.py", line 90, in unique_labels
    raise ValueError("Multi-label binary indicator input with "
ValueError: Multi-label binary indicator input with different numbers of labels
```

**Comment by tqbl** [comment]
Strange. I used the `predictions_test.csv` file you uploaded, and it worked for me. Just to make sure that it really is the file being read, can you modify this line (should be 284) in `task2/main.py`:
```
y_pred = io.read_metadata(path)
```
Replace `path` with the path to `predictions_test.csv`.
Or just print `path` and ensure it matches the file you gave me.

It might also be worth telling me what version of sklearn you are using.

I can also upload the source code I'm working with, though it should be the same.

**Comment by ghost** [comment]
The path is OK. 
My `scikit-learn` is version 0.20.0.

Could it be that `evaluation.py` line `class_scores = compute_audio_tagging_scores(y_true, y_pred, y_pred_b).T` can help? What are the dimensions for `y_true, y_pred, y_pred_b`? For me it is:
```
y_true (46,41)
y_pred (46,41)
y_pred_b (46,11)
```
Should this 11 be 41 too? 
Some guesssing, sorry. :-)

**Comment by tqbl** [comment]
Here is the source code I used (minus one change to the work path, which should have no effect): 
[task2.tar.gz](https://github.com/tqbl/dcase2018_task2/files/4181810/task2.tar.gz)

I noticed another error, different to yours, when downgrading pandas to 0.23.4 (the version specified in requirements.txt). It did not recognise `pd.CategoricalDtype`. If this occurs for you, either upgrade to a newer version of pandas (e.g. 0.25.3) or change that part of the code to `pd.core.dtypes.dtypes.CategoricalDtype`.

**Comment by tqbl** [comment]
> Could it be that `evaluation.py` line `class_scores = compute_audio_tagging_scores(y_true, y_pred, y_pred_b).T` can help? What are the dimensions for `y_true, y_pred, y_pred_b`? For me it is:
> 
> ```
> y_true (46,41)
> y_pred (46,41)
> y_pred_b (46,11)
> ```
> 
> Should this 11 be 41 too?
> Some guesssing, sorry. :-)

Yes, it should be `(46, 41)` like the rest. Are you sure the patch was fully applied? This is what the `binarize_predictions()` function in `inference.py` should look like:
```
def binarize_predictions(y_pred, threshold=-1):
    if threshold > 0:
        return (y_pred > threshold).astype(int)

    dtype = pd.CategoricalDtype(categories=range(y_pred.shape[1]))
    return utils.to_categorical(pd.Series(
        np.argmax(y_pred, axis=1), dtype=dtype))
```
If `pd.CategoricalDtype` gives you trouble, either upgrade pandas or replace with `pd.core.dtypes.dtypes.CategoricalDtype`. Edit: Use `pd.api.types.CategoricalDtype` for pandas <0.24 and `pd.CategoricalDtype` for pandas >=0.24.

**Comment by ghost** [comment]
Sorry, I applied the wrong patch (`eval_test.txt` instead of `eval_test2.txt`). 
I had to update the `pandas` too, but it works now. 
Thanks!

**Comment by tqbl** [comment]
Good to hear it worked. I've now pushed the relevant commit.
Eventually, I'll test the program with up-to-date packages so that I can update requirements.txt etc.
